ENV['EMAIL_USER_NAME'] = 'ozgecokyasar@gmail.com'
ENV['EMAIL_PASSWORD'] = 'OzgeAlviri123'
ENV['AWS_ACCESS_KEY_ID'] = 'AKIAI4G4IF4HA25EHJKQ'
ENV['AWS_SECRET_ACCESS_KEY_ID'] = '7bzn6UZsM9YN06lueCRFpwHtPY9lxlmiMWGUzLuu'
