ENV['EMAIL_USER_NAME'] = 'ozgecokyasar@gmail.com'
ENV['EMAIL_PASSWORD'] = 'OzgeAlviri123'
ENV['AWS_ACCESS_KEY_ID'] = 'AKIAJHLFKE44WY4EVSAQ'
ENV['AWS_SECRET_ACCESS_KEY_ID'] = 'hBvBUoZ2Zu3LdTBkTNWza5dMNJ+ChHLxtLDjCRx7'
