ENV['EMAIL_USER_NAME'] = 'ozgecokyasar@gmail.com'
ENV['EMAIL_PASSWORD'] = 'OzgeAlviri123'
ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIQSJPOJWYGBIUF6Q'
ENV['AWS_SECRET_ACCESS_KEY_ID'] = '88laqLnik+4ey+mVVDh3XhEFResaQ1KxzslgT9VK'
