ENV['EMAIL_USER_NAME'] = 'ozgecokyasar@gmail.com'
ENV['EMAIL_PASSWORD'] = 'OzgeAlviri123'
ENV['AWS_ACCESS_KEY_ID'] = 'AKIAJPT2G5LZEHH6P2DQ'
ENV['AWS_SECRET_ACCESS_KEY_ID'] = 'D4meQJ+4fvGe7+h7OjZA13pDYXh3QmHlV4GxMY92'
